/**
 * Report Controller
 * 
 * Handles PDF report generation for simulations
 */

const PDFDocument = require('pdfkit');

/**
 * @desc    Generate PDF report for a simulation
 * @route   POST /api/reports/generate
 * @access  Private
 */
const generateReport = async (req, res) => {
    try {
        const { params, results, canvasImage } = req.body;
        
        // Validate required data
        if (!params || !results) {
            return res.status(400).json({
                success: false,
                message: 'Missing simulation data'
            });
        }
        
        // Create PDF document
        const doc = new PDFDocument({
            size: 'A4',
            margin: 50,
            info: {
                Title: 'Projectile Motion Simulation Report',
                Author: 'Projectile Motion Simulator',
                Subject: 'Physics Simulation Report'
            }
        });
        
        // Set response headers for PDF download
        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', 'attachment; filename=simulation-report.pdf');
        
        // Pipe PDF to response
        doc.pipe(res);
        
        // === PDF Content ===
        
        // Header
        doc.fontSize(24)
           .fillColor('#264653')
           .text('Projectile Motion Simulation', { align: 'center' });
        
        doc.moveDown();
        doc.fontSize(12)
           .fillColor('#666')
           .text(`Generated: ${new Date().toLocaleString()}`, { align: 'center' });
        
        doc.moveDown(2);
        
        // Input Parameters Section
        doc.fontSize(16)
           .fillColor('#2a9d8f')
           .text('Input Parameters');
        
        doc.moveDown(0.5);
        doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#e0e0e0');
        doc.moveDown();
        
        doc.fontSize(11)
           .fillColor('#333');
        
        const paramData = [
            ['Initial Velocity (v₀)', `${params.initialVelocity} m/s`],
            ['Launch Angle (θ)', `${params.launchAngle}°`],
            ['Initial Height (h₀)', `${params.initialHeight} m`],
            ['Gravity (g)', `${params.gravity} m/s²`]
        ];
        
        paramData.forEach(([label, value]) => {
            doc.text(`${label}: `, { continued: true })
               .fillColor('#2a9d8f')
               .text(value)
               .fillColor('#333');
        });
        
        doc.moveDown(2);
        
        // Results Section
        doc.fontSize(16)
           .fillColor('#2a9d8f')
           .text('Simulation Results');
        
        doc.moveDown(0.5);
        doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#e0e0e0');
        doc.moveDown();
        
        doc.fontSize(11)
           .fillColor('#333');
        
        const resultData = [
            ['Maximum Height (y_max)', `${results.maxHeight.toFixed(2)} m`],
            ['Horizontal Range (x_max)', `${results.range.toFixed(2)} m`],
            ['Total Flight Time', `${results.flightTime.toFixed(2)} s`],
            ['Final Velocity', `${results.finalVelocity.toFixed(2)} m/s`]
        ];
        
        resultData.forEach(([label, value]) => {
            doc.text(`${label}: `, { continued: true })
               .fillColor('#2a9d8f')
               .text(value)
               .fillColor('#333');
        });
        
        doc.moveDown(2);
        
        // Formulas Section
        doc.fontSize(16)
           .fillColor('#2a9d8f')
           .text('Physics Formulas Used');
        
        doc.moveDown(0.5);
        doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#e0e0e0');
        doc.moveDown();
        
        doc.fontSize(10)
           .fillColor('#666');
        
        doc.text('Trajectory Equation:');
        doc.text('y = x·tan(θ) - (g·x²)/(2·v₀²·cos²(θ))', { indent: 20 });
        doc.moveDown();
        
        doc.text('Position at time t:');
        doc.text('x(t) = v₀·cos(θ)·t', { indent: 20 });
        doc.text('y(t) = h₀ + v₀·sin(θ)·t - ½·g·t²', { indent: 20 });
        doc.moveDown();
        
        doc.text('Maximum Height:');
        doc.text('y_max = h₀ + (v₀²·sin²(θ))/(2·g)', { indent: 20 });
        
        // Footer
        doc.moveDown(4);
        doc.fontSize(9)
           .fillColor('#999')
           .text('Generated by Projectile Motion Simulator', { align: 'center' });
        doc.text('For educational purposes', { align: 'center' });
        
        // Finalize PDF
        doc.end();
        
    } catch (error) {
        console.error('Generate report error:', error);
        res.status(500).json({
            success: false,
            message: 'Error generating report'
        });
    }
};

module.exports = {
    generateReport
};
